"""Source trust, classification, and execution authorization contracts."""

from .policy import (
    AuthorizationError,
    BuildAuthorization,
    BuildAuthorizationVerifier,
    BuildRequest,
    BuildRequestDeclaration,
    DirectBuildAuthorizationVerifier,
    DirectObservationExecutionAuthorizationVerifier,
    FailClosedBuildAuthorizationVerifier,
    FailClosedObservationExecutionAuthorizationVerifier,
    FindingSeverity,
    LiveBuildAuthorizationVerifier,
    LiveObservationExecutionAuthorizationVerifier,
    ObservationExecutionAuthorization,
    ObservationExecutionAuthorizationVerifier,
    ObservationRequest,
    OriginAttestation,
    SecurityClassification,
    SecurityFinding,
    SecurityPolicy,
    SecurityProfile,
    adapt_unreleased_post_v011_security_document,
    normalize_security_document,
)
from .scanning import (
    AuthorizationRevocation,
    AuthorizationRevocationSet,
    RuleBasedSourceScanner,
    ScanRule,
    SecurityScanReport,
    SourceModule,
    baseline_cpp_rules,
    baseline_javascript_rules,
    baseline_python_rules,
    baseline_rust_rules,
    baseline_swift_rules,
)

# Policy exports must exist before isolation imports the domain-contract package,
# whose lifecycle records refer back to this public security boundary.
# isort: split
from .isolation import (
    ContainmentControl,
    ContainmentStage,
    IsolationDecision,
    IsolationDecisionStatus,
    IsolationEvidenceAuthentication,
    IsolationLevel,
    IsolationObservation,
    IsolationPolicy,
    IsolationPolicyError,
    IsolationRequest,
    StageIsolationRule,
    evaluate_isolation_policy,
    mandatory_controls_for,
)

__all__ = [
    "ContainmentControl",
    "ContainmentStage",
    "IsolationDecision",
    "IsolationDecisionStatus",
    "IsolationEvidenceAuthentication",
    "IsolationLevel",
    "IsolationObservation",
    "IsolationPolicy",
    "IsolationPolicyError",
    "IsolationRequest",
    "StageIsolationRule",
    "evaluate_isolation_policy",
    "mandatory_controls_for",
    "AuthorizationRevocation",
    "AuthorizationRevocationSet",
    "AuthorizationError",
    "BuildAuthorization",
    "BuildAuthorizationVerifier",
    "BuildRequest",
    "BuildRequestDeclaration",
    "DirectBuildAuthorizationVerifier",
    "DirectObservationExecutionAuthorizationVerifier",
    "FailClosedBuildAuthorizationVerifier",
    "FailClosedObservationExecutionAuthorizationVerifier",
    "FindingSeverity",
    "LiveBuildAuthorizationVerifier",
    "LiveObservationExecutionAuthorizationVerifier",
    "ObservationExecutionAuthorization",
    "ObservationExecutionAuthorizationVerifier",
    "ObservationRequest",
    "OriginAttestation",
    "RuleBasedSourceScanner",
    "ScanRule",
    "SecurityClassification",
    "SecurityFinding",
    "SecurityPolicy",
    "SecurityProfile",
    "SecurityScanReport",
    "SourceModule",
    "baseline_cpp_rules",
    "baseline_javascript_rules",
    "baseline_python_rules",
    "baseline_rust_rules",
    "baseline_swift_rules",
    "adapt_unreleased_post_v011_security_document",
    "normalize_security_document",
]
