"""Model-provider adapters."""

from .coding_cli import (
    CODING_CLIS,
    LIFECYCLE_DRIVER_ENVIRONMENT_KEYS,
    CodingCliError,
    CodingCliGeneration,
    CodingCliIsolation,
    CodingCliSelection,
    CodingCliSourceGenerator,
    CodingCliTaskResult,
    CodingCliTaskRunner,
    GenerationRecipe,
    RecipeCppLibraryBuild,
    RecipeDeploymentUnit,
    RecipeDocument,
    RecipeFlavor,
    RecipeLibraryDependency,
    RecipeSkill,
    apply_flavor_selectors,
    inspect_coding_cli_authentication,
    lifecycle_driver_environment,
    select_coding_cli,
)
from .inherited_session import (
    CODING_PROVIDER_ENVIRONMENT,
    INHERITED_SESSION_PROVIDER,
    DirectoryInheritedSessionCoordinator,
    DirectoryInheritedSessionTransport,
    InheritedSessionCancellation,
    InheritedSessionCustody,
    InheritedSessionDelivery,
    InheritedSessionError,
    InheritedSessionHandoffResult,
    InheritedSessionProviderAdapter,
    InheritedSessionProviderConfig,
    InheritedSessionReceivedRequest,
    InheritedSessionSelection,
    InheritedSessionSourceGenerator,
    InheritedSessionTransport,
    selected_coding_provider,
)
from .inverse import CodingCliInverseTranslator
from .native_sdk_recipe import RecipeNativeSdkDependency
from .openai_compatible import (
    EnvironmentCredentialResolver,
    HTTPResponse,
    ModelAdapterError,
    OpenAICompatibleResponsesProvider,
    StructuredModelResult,
    UrllibJSONTransport,
)
from .portable_application import (
    PORTABLE_APPLICATION_SCHEMA,
    SUPPORTED_IMPLEMENTATION_LANGUAGES,
    PortableApplicationError,
    portable_source_entrypoint,
    validate_portable_application,
)
from .portfolio import ModelProviderPortfolio, PortfolioProviderError
from .semantic_comparison import (
    CodingCliSemanticComparator,
    CodingCliSemanticComparisonResult,
    SemanticComparisonTaskRunner,
)

__all__ = [
    "CODING_CLIS",
    "CODING_PROVIDER_ENVIRONMENT",
    "INHERITED_SESSION_PROVIDER",
    "LIFECYCLE_DRIVER_ENVIRONMENT_KEYS",
    "CodingCliError",
    "CodingCliGeneration",
    "CodingCliInverseTranslator",
    "CodingCliIsolation",
    "CodingCliSelection",
    "CodingCliSourceGenerator",
    "CodingCliSemanticComparator",
    "CodingCliSemanticComparisonResult",
    "CodingCliTaskResult",
    "CodingCliTaskRunner",
    "DirectoryInheritedSessionCoordinator",
    "DirectoryInheritedSessionTransport",
    "EnvironmentCredentialResolver",
    "GenerationRecipe",
    "HTTPResponse",
    "InheritedSessionCancellation",
    "InheritedSessionCustody",
    "InheritedSessionDelivery",
    "InheritedSessionError",
    "InheritedSessionHandoffResult",
    "InheritedSessionProviderAdapter",
    "InheritedSessionProviderConfig",
    "InheritedSessionReceivedRequest",
    "InheritedSessionSelection",
    "InheritedSessionSourceGenerator",
    "InheritedSessionTransport",
    "ModelAdapterError",
    "ModelProviderPortfolio",
    "OpenAICompatibleResponsesProvider",
    "PORTABLE_APPLICATION_SCHEMA",
    "PortfolioProviderError",
    "PortableApplicationError",
    "SUPPORTED_IMPLEMENTATION_LANGUAGES",
    "RecipeDocument",
    "RecipeDeploymentUnit",
    "RecipeFlavor",
    "RecipeLibraryDependency",
    "RecipeNativeSdkDependency",
    "RecipeCppLibraryBuild",
    "RecipeSkill",
    "StructuredModelResult",
    "SemanticComparisonTaskRunner",
    "UrllibJSONTransport",
    "apply_flavor_selectors",
    "inspect_coding_cli_authentication",
    "lifecycle_driver_environment",
    "portable_source_entrypoint",
    "select_coding_cli",
    "selected_coding_provider",
    "validate_portable_application",
]
