"""Human-owned Component intent without resolver-owned content identities."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any, ClassVar
from urllib.parse import urlsplit

from .._validation import (
    bool_value,
    contract_fields,
    fail,
    fields,
    parse_tuple,
    string_tuple,
    string_value,
    unique,
)
from ..capabilities import CapabilityRequirement, DependencyKind
from ..components import Entrypoint, resolve_component_kind, validate_component_kind
from ..executable_components._common import portable_name, tuple_value
from ..flavors import FlavorSlot
from ..identity import ComponentCoordinate, ContentIdentity, contract_identity
from ..library_imports import AuthoredLibraryImport, validate_library_imports
from ..paths import canonical_relative_posix_path
from ..provider_resolution import ProviderResolutionDeclaration
from ..repositories import RepositoryRevisionSelector, RepositorySourceDependency
from ..versioning import semantic_version

COMPONENT_CONTENT_SELECTOR_SCHEMA = (
    "urn:literate-ai:schema:v2:component-content-selector"
)
COMPONENT_AUTHORING_SCHEMA = "urn:literate-ai:schema:v2:component-authoring"
COMPONENT_ASSET_SELECTOR_SCHEMA = "urn:literate-ai:schema:v2:component-asset-selector"


def _asset_source(value: object, path: str) -> str:
    raw = string_value(value, path, max_length=8192)
    parsed = urlsplit(raw)
    if parsed.scheme:
        if parsed.scheme not in {"http", "https", "project"}:
            fail(path, "must use a relative path, project:/// URI, or HTTP(S) URI")
        if parsed.fragment:
            fail(path, "must not contain a URI fragment")
        if parsed.scheme == "project":
            if parsed.netloc or parsed.query or not parsed.path.startswith("/"):
                fail(path, "project URI must have the form project:///path")
            try:
                canonical_relative_posix_path(
                    parsed.path.removeprefix("/"), label="project asset path"
                )
            except (TypeError, ValueError) as exc:
                fail(path, str(exc))
        elif not parsed.netloc or parsed.username is not None:
            fail(path, "HTTP(S) URI must name a host and must not embed credentials")
        return raw
    try:
        canonical_relative_posix_path(raw, label="component asset source")
    except (TypeError, ValueError) as exc:
        fail(path, str(exc))
    return raw


@dataclass(frozen=True, slots=True)
class ComponentAssetSelector:
    """Human-owned location and runtime projection for non-generated bytes."""

    asset_id: str
    source: str
    path: str
    role: str
    media_type: str = "application/octet-stream"
    pin: ContentIdentity | None = None

    SCHEMA: ClassVar[str] = COMPONENT_ASSET_SELECTOR_SCHEMA

    def __post_init__(self) -> None:
        portable_name(self.asset_id, "ComponentAssetSelector.asset_id")
        _asset_source(self.source, "ComponentAssetSelector.source")
        try:
            canonical_relative_posix_path(self.path, label="component asset path")
        except (TypeError, ValueError) as exc:
            fail("ComponentAssetSelector.path", str(exc))
        portable_name(self.role, "ComponentAssetSelector.role")
        string_value(self.media_type, "ComponentAssetSelector.media_type")
        if not isinstance(self.pin, (ContentIdentity, type(None))):
            fail("ComponentAssetSelector.pin", "must be a ContentIdentity or null")

    @property
    def identity(self) -> ContentIdentity:
        return contract_identity(self)

    def to_dict(self) -> dict[str, object]:
        value: dict[str, object] = {
            "schema": self.SCHEMA,
            "asset_id": self.asset_id,
            "source": self.source,
            "path": self.path,
            "role": self.role,
            "media_type": self.media_type,
            "pin": None if self.pin is None else self.pin.to_dict(),
        }
        return value

    @classmethod
    def from_dict(
        cls, value: Any, *, path: str = "ComponentAssetSelector"
    ) -> ComponentAssetSelector:
        data = contract_fields(
            value,
            path=path,
            schema_uri=cls.SCHEMA,
            required=frozenset(
                {"asset_id", "source", "path", "role", "media_type", "pin"}
            ),
        )
        pin = data["pin"]
        return cls(
            asset_id=portable_name(data["asset_id"], f"{path}.asset_id"),
            source=_asset_source(data["source"], f"{path}.source"),
            path=string_value(data["path"], f"{path}.path"),
            role=portable_name(data["role"], f"{path}.role"),
            media_type=string_value(data["media_type"], f"{path}.media_type"),
            pin=(
                None
                if pin is None
                else ContentIdentity.from_dict(pin, path=f"{path}.pin")
            ),
        )


def _canonical(
    values: object,
    *,
    path: str,
    expected_type: type[Any],
    key: Any,
    label: str,
) -> tuple[Any, ...]:
    items = tuple_value(values, path)
    if len(items) > 256 or any(not isinstance(item, expected_type) for item in items):
        fail(path, f"must contain at most 256 {label} values")
    keys = tuple(key(item) for item in items)
    unique(keys, path, label)
    if keys != tuple(sorted(keys)):
        fail(path, f"must use canonical {label} order")
    return items


def _catalog_relative_uri(value: object, path: str) -> str:
    raw = string_value(value, path, max_length=4096)
    candidate = PurePosixPath(raw)
    if (
        candidate.is_absolute()
        or "\\" in raw
        or "://" in raw
        or any(character.isspace() for character in raw)
        or any(part in {"", ".", ".."} for part in candidate.parts)
        or candidate.as_posix() != raw
    ):
        fail(path, "must be a canonical catalog-relative POSIX path")
    return raw


@dataclass(frozen=True, slots=True)
class ComponentContentSelector:
    """An authored catalog-relative reference with an optional deliberate pin."""

    kind: str
    uri: str
    pin: ContentIdentity | None = None

    SCHEMA: ClassVar[str] = COMPONENT_CONTENT_SELECTOR_SCHEMA

    def __post_init__(self) -> None:
        portable_name(self.kind, "ComponentContentSelector.kind")
        _catalog_relative_uri(self.uri, "ComponentContentSelector.uri")
        if not isinstance(self.pin, (ContentIdentity, type(None))):
            fail("ComponentContentSelector.pin", "must be a ContentIdentity or null")

    @property
    def identity(self) -> ContentIdentity:
        return contract_identity(self)

    def to_dict(self) -> dict[str, object]:
        value: dict[str, object] = {
            "schema": self.SCHEMA,
            "kind": self.kind,
            "uri": self.uri,
            "pin": None if self.pin is None else self.pin.to_dict(),
        }
        return value

    @classmethod
    def from_dict(
        cls, value: Any, *, path: str = "ComponentContentSelector"
    ) -> ComponentContentSelector:
        data = contract_fields(
            value,
            path=path,
            schema_uri=cls.SCHEMA,
            required=frozenset({"kind", "uri", "pin"}),
        )
        pin = data["pin"]
        return cls(
            kind=portable_name(data["kind"], f"{path}.kind"),
            uri=_catalog_relative_uri(data["uri"], f"{path}.uri"),
            pin=(
                None
                if pin is None
                else ContentIdentity.from_dict(pin, path=f"{path}.pin")
            ),
        )


@dataclass(frozen=True, slots=True)
class AuthoredProvidedCapability:
    """A provided capability and the selector for its public interface, if any."""

    name: str
    version: str
    interface: ComponentContentSelector | None

    def __post_init__(self) -> None:
        portable_name(self.name, "AuthoredProvidedCapability.name")
        semantic_version(self.version, "AuthoredProvidedCapability.version")
        if not isinstance(self.interface, (ComponentContentSelector, type(None))):
            fail(
                "AuthoredProvidedCapability.interface",
                "must be a ComponentContentSelector or null",
            )
        if (
            self.interface is not None
            and self.interface.kind != "public-interface-contract"
        ):
            fail(
                "AuthoredProvidedCapability.interface.kind",
                "must be 'public-interface-contract'",
            )

    def to_dict(self) -> dict[str, object]:
        return {
            "name": self.name,
            "version": self.version,
            "interface": (None if self.interface is None else self.interface.to_dict()),
        }

    @classmethod
    def from_dict(
        cls, value: Any, *, path: str = "AuthoredProvidedCapability"
    ) -> AuthoredProvidedCapability:
        data = fields(
            value,
            path=path,
            required=frozenset({"name", "version", "interface"}),
        )
        interface = data["interface"]
        return cls(
            name=portable_name(data["name"], f"{path}.name"),
            version=semantic_version(data["version"], f"{path}.version"),
            interface=(
                None
                if interface is None
                else ComponentContentSelector.from_dict(
                    interface, path=f"{path}.interface"
                )
            ),
        )


@dataclass(frozen=True, slots=True)
class AuthoredRepositorySourceDependency:
    """Mutable repository selection intent, distinct from an exact source lock."""

    dependency_id: str
    repository_url: str
    revision_selector: RepositoryRevisionSelector
    dependency_kind: DependencyKind
    optional: bool = False
    integration_contract: ComponentContentSelector | None = None

    def __post_init__(self) -> None:
        # Reuse the repository contract's URL, ID, selector, kind, and optionality
        # validation while keeping its exact ContentReference out of authoring.
        RepositorySourceDependency(
            self.dependency_id,
            self.repository_url,
            self.revision_selector,
            self.dependency_kind,
            self.optional,
            None,
        )
        if not isinstance(
            self.integration_contract, (ComponentContentSelector, type(None))
        ):
            fail(
                "AuthoredRepositorySourceDependency.integration_contract",
                "must be a ComponentContentSelector or null",
            )
        if (
            self.integration_contract is not None
            and self.integration_contract.kind != "integration-contract"
        ):
            fail(
                "AuthoredRepositorySourceDependency.integration_contract.kind",
                "must be 'integration-contract'",
            )

    def to_dict(self) -> dict[str, object]:
        return {
            "dependency_id": self.dependency_id,
            "repository_url": self.repository_url,
            "revision_selector": self.revision_selector.to_dict(),
            "dependency_kind": self.dependency_kind.value,
            "optional": self.optional,
            "integration_contract": (
                None
                if self.integration_contract is None
                else self.integration_contract.to_dict()
            ),
        }

    @classmethod
    def from_dict(
        cls, value: Any, *, path: str = "AuthoredRepositorySourceDependency"
    ) -> AuthoredRepositorySourceDependency:
        data = fields(
            value,
            path=path,
            required=frozenset(
                {
                    "dependency_id",
                    "repository_url",
                    "revision_selector",
                    "dependency_kind",
                    "optional",
                    "integration_contract",
                }
            ),
        )
        try:
            kind = DependencyKind(data["dependency_kind"])
        except (TypeError, ValueError):
            fail(f"{path}.dependency_kind", "must be a DependencyKind")
        integration = data["integration_contract"]
        return cls(
            dependency_id=string_value(data["dependency_id"], f"{path}.dependency_id"),
            repository_url=string_value(
                data["repository_url"], f"{path}.repository_url"
            ),
            revision_selector=RepositoryRevisionSelector.from_dict(
                data["revision_selector"], path=f"{path}.revision_selector"
            ),
            dependency_kind=kind,
            optional=bool_value(data["optional"], f"{path}.optional"),
            integration_contract=(
                None
                if integration is None
                else ComponentContentSelector.from_dict(
                    integration, path=f"{path}.integration_contract"
                )
            ),
        )


@dataclass(frozen=True, slots=True)
class ComponentAuthoring:
    """Serialization-neutral projection of the human-owned ``component.md`` intent."""

    coordinate: ComponentCoordinate
    version: str
    display_name: str
    description: str
    profiles: tuple[str, ...]
    sample: bool
    provides: tuple[AuthoredProvidedCapability, ...]
    requires: tuple[CapabilityRequirement, ...]
    specification_provider: str
    specification_roots: tuple[str, ...]
    authoring_inputs: tuple[ComponentContentSelector, ...]
    workflow_definition: ComponentContentSelector
    routing_policy: ComponentContentSelector
    flavor_slots: tuple[FlavorSlot, ...]
    entrypoints: tuple[Entrypoint, ...]
    acceptance_contracts: tuple[ComponentContentSelector, ...]
    inheritable: bool = True
    source_dependencies: tuple[AuthoredRepositorySourceDependency, ...] = ()
    assets: tuple[ComponentAssetSelector, ...] = ()
    provider_resolutions: tuple[ProviderResolutionDeclaration, ...] = ()
    kind: str = ""
    library_imports: tuple[AuthoredLibraryImport, ...] = ()

    SCHEMA: ClassVar[str] = COMPONENT_AUTHORING_SCHEMA

    def __post_init__(self) -> None:
        if not isinstance(self.coordinate, ComponentCoordinate):
            fail("ComponentAuthoring.coordinate", "must be a ComponentCoordinate")
        semantic_version(self.version, "ComponentAuthoring.version")
        string_value(self.display_name, "ComponentAuthoring.display_name")
        string_value(
            self.description,
            "ComponentAuthoring.description",
            nonempty=False,
            max_length=16384,
        )
        profiles = tuple_value(self.profiles, "ComponentAuthoring.profiles")
        for index, profile in enumerate(profiles):
            portable_name(profile, f"ComponentAuthoring.profiles[{index}]")
        unique(profiles, "ComponentAuthoring.profiles")
        if profiles != tuple(sorted(profiles)):
            fail("ComponentAuthoring.profiles", "must use canonical profile order")
        bool_value(self.sample, "ComponentAuthoring.sample")
        bool_value(self.inheritable, "ComponentAuthoring.inheritable")
        _canonical(
            self.provides,
            path="ComponentAuthoring.provides",
            expected_type=AuthoredProvidedCapability,
            key=lambda item: item.name,
            label="capability names",
        )
        _canonical(
            self.requires,
            path="ComponentAuthoring.requires",
            expected_type=CapabilityRequirement,
            key=lambda item: item.requirement_id,
            label="requirement IDs",
        )
        for index, requirement in enumerate(self.requires):
            portable_name(
                requirement.requirement_id,
                f"ComponentAuthoring.requires[{index}].requirement_id",
            )
            portable_name(
                requirement.capability,
                f"ComponentAuthoring.requires[{index}].capability",
            )
        string_value(
            self.specification_provider, "ComponentAuthoring.specification_provider"
        )
        roots = tuple_value(
            self.specification_roots, "ComponentAuthoring.specification_roots"
        )
        if not roots:
            fail("ComponentAuthoring.specification_roots", "must not be empty")
        for index, root in enumerate(roots):
            _catalog_relative_uri(
                root, f"ComponentAuthoring.specification_roots[{index}]"
            )
        unique(roots, "ComponentAuthoring.specification_roots")
        _canonical(
            self.authoring_inputs,
            path="ComponentAuthoring.authoring_inputs",
            expected_type=ComponentContentSelector,
            key=lambda item: (item.kind, item.uri),
            label="authoring selectors",
        )
        for field_name in ("workflow_definition", "routing_policy"):
            if not isinstance(getattr(self, field_name), ComponentContentSelector):
                fail(
                    f"ComponentAuthoring.{field_name}",
                    "must be a ComponentContentSelector",
                )
        if self.workflow_definition.kind != "workflow":
            fail("ComponentAuthoring.workflow_definition.kind", "must be 'workflow'")
        if self.routing_policy.kind != "routing-policy":
            fail("ComponentAuthoring.routing_policy.kind", "must be 'routing-policy'")
        _canonical(
            self.flavor_slots,
            path="ComponentAuthoring.flavor_slots",
            expected_type=FlavorSlot,
            key=lambda item: item.slot_id,
            label="Flavor slot IDs",
        )
        _canonical(
            self.entrypoints,
            path="ComponentAuthoring.entrypoints",
            expected_type=Entrypoint,
            key=lambda item: item.name,
            label="entrypoint names",
        )
        unique(
            tuple(item.resolved_deployment_unit for item in self.entrypoints),
            "ComponentAuthoring.entrypoints",
            "resolved deployment units",
        )
        _canonical(
            self.acceptance_contracts,
            path="ComponentAuthoring.acceptance_contracts",
            expected_type=ComponentContentSelector,
            key=lambda item: (item.kind, item.uri),
            label="acceptance selectors",
        )
        if any(
            item.kind != "acceptance-contract" for item in self.acceptance_contracts
        ):
            fail(
                "ComponentAuthoring.acceptance_contracts",
                "must contain only acceptance-contract selectors",
            )
        _canonical(
            self.source_dependencies,
            path="ComponentAuthoring.source_dependencies",
            expected_type=AuthoredRepositorySourceDependency,
            key=lambda item: item.dependency_id,
            label="repository dependency IDs",
        )
        _canonical(
            self.assets,
            path="ComponentAuthoring.assets",
            expected_type=ComponentAssetSelector,
            key=lambda item: item.asset_id,
            label="asset IDs",
        )
        _canonical(
            self.provider_resolutions,
            path="ComponentAuthoring.provider_resolutions",
            expected_type=ProviderResolutionDeclaration,
            key=lambda item: item.resolution_id,
            label="provider resolution IDs",
        )
        unique(
            tuple(item.path for item in self.assets),
            "ComponentAuthoring.assets",
            "asset paths",
        )
        validate_component_kind(
            resolve_component_kind(self.kind, self.entrypoints),
            self.entrypoints,
        )

        validate_library_imports(
            self.library_imports,
            kind=self.resolved_kind,
            capabilities=tuple(item.name for item in self.provides),
        )
        if self.library_imports and any(
            item.interface is None for item in self.provides
        ):
            fail("ComponentAuthoring.library_imports", "requires public interfaces")

    @property
    def resolved_kind(self) -> str:
        return resolve_component_kind(self.kind, self.entrypoints).value

    @property
    def identity(self) -> ContentIdentity:
        return contract_identity(self)

    def to_dict(self) -> dict[str, object]:
        value: dict[str, object] = {
            "schema": self.SCHEMA,
            "coordinate": self.coordinate.to_dict(),
            "version": self.version,
            "display_name": self.display_name,
            "description": self.description,
            "profiles": list(self.profiles),
            "sample": self.sample,
            "provides": [item.to_dict() for item in self.provides],
            "requires": [item.to_dict() for item in self.requires],
            "specification_provider": self.specification_provider,
            "specification_roots": list(self.specification_roots),
            "authoring_inputs": [item.to_dict() for item in self.authoring_inputs],
            "workflow_definition": self.workflow_definition.to_dict(),
            "routing_policy": self.routing_policy.to_dict(),
            "flavor_slots": [item.to_dict() for item in self.flavor_slots],
            "entrypoints": [item.to_dict() for item in self.entrypoints],
            "acceptance_contracts": [
                item.to_dict() for item in self.acceptance_contracts
            ],
            "source_dependencies": [
                item.to_dict() for item in self.source_dependencies
            ],
        }
        # Empty assets predate this additive field. Preserve their established
        # authoring identity while making every non-empty declaration explicit.
        if self.assets:
            value["assets"] = [item.to_dict() for item in self.assets]
        if self.provider_resolutions:
            value["provider_resolutions"] = [
                item.to_dict() for item in self.provider_resolutions
            ]
        if not self.inheritable:
            value["inheritable"] = False
        if self.kind:
            value["kind"] = self.kind
        if self.library_imports:
            value["library_imports"] = [item.to_dict() for item in self.library_imports]
        return value

    @classmethod
    def from_dict(
        cls, value: Any, *, path: str = "ComponentAuthoring"
    ) -> ComponentAuthoring:
        data = contract_fields(
            value,
            path=path,
            schema_uri=cls.SCHEMA,
            required=frozenset(
                {
                    "coordinate",
                    "version",
                    "display_name",
                    "description",
                    "profiles",
                    "sample",
                    "provides",
                    "requires",
                    "specification_provider",
                    "specification_roots",
                    "authoring_inputs",
                    "workflow_definition",
                    "routing_policy",
                    "flavor_slots",
                    "entrypoints",
                    "acceptance_contracts",
                    "source_dependencies",
                }
            ),
            optional=frozenset(
                {
                    "assets",
                    "inheritable",
                    "provider_resolutions",
                    "kind",
                    "library_imports",
                }
            ),
        )
        return cls(
            coordinate=ComponentCoordinate.from_dict(
                data["coordinate"], path=f"{path}.coordinate"
            ),
            version=semantic_version(data["version"], f"{path}.version"),
            display_name=string_value(data["display_name"], f"{path}.display_name"),
            description=string_value(
                data["description"],
                f"{path}.description",
                nonempty=False,
                max_length=16384,
            ),
            profiles=string_tuple(data["profiles"], f"{path}.profiles"),
            sample=bool_value(data["sample"], f"{path}.sample"),
            inheritable=bool_value(
                data.get("inheritable", True), f"{path}.inheritable"
            ),
            provides=parse_tuple(
                data["provides"],
                f"{path}.provides",
                AuthoredProvidedCapability.from_dict,
            ),
            requires=parse_tuple(
                data["requires"],
                f"{path}.requires",
                CapabilityRequirement.from_dict,
            ),
            specification_provider=string_value(
                data["specification_provider"], f"{path}.specification_provider"
            ),
            specification_roots=string_tuple(
                data["specification_roots"], f"{path}.specification_roots"
            ),
            authoring_inputs=parse_tuple(
                data["authoring_inputs"],
                f"{path}.authoring_inputs",
                ComponentContentSelector.from_dict,
            ),
            workflow_definition=ComponentContentSelector.from_dict(
                data["workflow_definition"], path=f"{path}.workflow_definition"
            ),
            routing_policy=ComponentContentSelector.from_dict(
                data["routing_policy"], path=f"{path}.routing_policy"
            ),
            flavor_slots=parse_tuple(
                data["flavor_slots"], f"{path}.flavor_slots", FlavorSlot.from_dict
            ),
            entrypoints=parse_tuple(
                data["entrypoints"], f"{path}.entrypoints", Entrypoint.from_dict
            ),
            acceptance_contracts=parse_tuple(
                data["acceptance_contracts"],
                f"{path}.acceptance_contracts",
                ComponentContentSelector.from_dict,
            ),
            source_dependencies=parse_tuple(
                data["source_dependencies"],
                f"{path}.source_dependencies",
                AuthoredRepositorySourceDependency.from_dict,
            ),
            assets=parse_tuple(
                data.get("assets", []),
                f"{path}.assets",
                ComponentAssetSelector.from_dict,
            ),
            provider_resolutions=parse_tuple(
                data.get("provider_resolutions", []),
                f"{path}.provider_resolutions",
                ProviderResolutionDeclaration.from_dict,
            ),
            kind=string_value(data["kind"], f"{path}.kind") if "kind" in data else "",
            library_imports=parse_tuple(
                data.get("library_imports", []),
                f"{path}.library_imports",
                AuthoredLibraryImport.from_dict,
            ),
        )


__all__ = [
    "COMPONENT_ASSET_SELECTOR_SCHEMA",
    "COMPONENT_AUTHORING_SCHEMA",
    "COMPONENT_CONTENT_SELECTOR_SCHEMA",
    "AuthoredProvidedCapability",
    "AuthoredRepositorySourceDependency",
    "ComponentAssetSelector",
    "ComponentAuthoring",
    "ComponentContentSelector",
]
